openapi: 3.0.0
info:
  title: Admin Service
  version: 1.0.0
  description: API documentation for admin-service
paths:
  /admin/health:
    get:
      summary: health_check
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
  /admin/:
    get:
      summary: root
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
tags: []
