openapi: 3.1.0
info:
  title: Admin Service
  description: Admin management service for wealth manager platform.
  version: 0.1.0
  contact:
    name: Wealth Manager Team
    url: https://github.com/sri-akshat/wealth-manager
  license:
    name: Private
paths:
  /health:
    get:
      tags:
      - system
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /:
    get:
      tags:
      - system
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    MessageResponse:
      properties:
        message:
          type: string
          title: Message
        service:
          type: string
          title: Service
        version:
          type: string
          title: Version
        status:
          type: string
          title: Status
      type: object
      required:
      - message
      - service
      - version
      - status
      title: MessageResponse
tags:
- name: system
  description: System maintenance operations
