openapi: 3.1.0
info:
  title: Notification Service
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    MessageResponse:
      properties:
        message:
          type: string
          title: Message
        service:
          type: string
          title: Service
        version:
          type: string
          title: Version
        status:
          type: string
          title: Status
      type: object
      required:
      - message
      - service
      - version
      - status
      title: MessageResponse
