openapi: 3.0.0
info:
  title: Transaction Service
  version: 1.0.0
  description: API documentation for transaction-service
paths:
  /transactions/health:
    get:
      summary: health_check
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
  /transactions/:
    get:
      summary: root
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
tags: []
