openapi: 3.0.0
info:
  title: kyc-service API
  version: 1.0.0
  description: API specification for kyc-service
paths:
  /:
    get:
      tags:
      - system
      summary: Root endpoint that provides basic service information.
      description: Returns service name, version, and status.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                  version:
                    type: string
                  status:
                    type: string
  /health:
    get:
      tags:
      - system
      summary: Health check endpoint.
      description: Check if the service is healthy.
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
tags:
- name: system
  description: System maintenance operations
