openapi: 3.0.0
info:
  title: KYC Service
  version: 1.0.0
  description: API documentation for kyc-service
paths:
  /kyc/health:
    get:
      summary: health_check
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
  /kyc/:
    get:
      summary: root
      description: null
      tags: []
      responses:
        '200':
          description: Successful Response
tags: []
