name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/services/investment-service/src
    strategy:
      matrix:
        python-version: [3.12]  # Adjust versions as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies Recursively
        run: |
          # Find and install every requirements.txt in the repo
          find . -name "requirements.txt" -exec pip install -r {} \;

      - name: Run Tests with Coverage
        run: |
          # Adjust the --cov flag to point to your source directory if needed
          pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sri-akshat/wealth-manager